### ISSUE TITLE
Cache in $http

### ISSUE THREAD

**Issue by rkusuma** [guylabs/angular-spring-data-rest#14]
Hi @guylabs

Can i add use `cache: true` in $http ?

**Comment by guylabs** [comment]
Hi Romy,

well currently the `$http` is configured in the `fetchFunction` and there is no configuration option to pass `$http` options to it.

The problem with the cache set to true is when you call finder methods which do not always return the same response. If it is an id based request then it is ok but not otherwise.

Fo that I would use the standard HTTP caching of the browsers as there you can also revalidate it and it is stored on the disk and not like the angular cache which is renewed after each page refresh.

So therefore I would not use it this way, but I could add a new configuration option for the config object of the `$http` service and then you could change it how you like to.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Closed due to inactivity.
