### ISSUE TITLE
How to chain resources calls

### ISSUE THREAD

**Issue by sydneyhenrard** [guylabs/angular-spring-data-rest#20]
I would like to call several resources like that:

```
POST http://lolcahost:54000/api/v1/portfolios
PATCH http://lolcahost:54000/api/v1/portfolios/1
GET http://lolcahost:54000/api/v1/portfolios/1/evaluate
GET http://lolcahost:54000/api/v1/portfolios/1
GET http://lolcahost:54000/api/v1/portfolios/1/summaries
Process the output
```

I wrote that code but I am not sure it's the correct way to use `SpringDataRestAdapter`. I also have an issue with one of the processed response that does not have a _resources object.

```
// POST http://lolcahost:54000/api/v1/portfolios
var myHttpPromise = $http.post('http://localhost:54000/api/v1/portfolios', {});
SpringDataRestAdapter.process(myHttpPromise)
    .then(function (processedResponse) {
        // PATCH http://lolcahost:54000/api/v1/portfolios/1
        var self = processedResponse._links.self.href;
        var data = {};
        return SpringDataRestAdapter.process($http.patch(self, data));
    })
    .then(function (processedResponse) {
    	// GET http://lolcahost:54000/api/v1/portfolios/1/evaluate
        var resources = processedResponse._resources("self/:id", {id: "evaluate"});
        return SpringDataRestAdapter.process(resources.get());
    })
    .then(function (processedResponse) {
    	// GET http://lolcahost:54000/api/v1/portfolios/1
        console.log(processedResponse);
        // ERROR processedResponse does not have a _resources property
        var resources = processedResponse._resources("self");
        return SpringDataRestAdapter.process(resources.get());
    .then(function (processedResponse) {
	    // GET http://lolcahost:54000/api/v1/portfolios/1/summaries
        return processedResponse._resources('summaries');
    })
    .then(function (summaries) {
    	// Process the output
        console.log(summaries);
    }, function (response) {
        console.log(response);
        console.log(response.data.error);
        logger.error(response.data.error);
    });
```

**Comment by guylabs** [comment]
Hi @sydneyhenrard, 

sorry for my late reply but I was in vacations. The chaining looks good but the `resources.get()` won't return the proper promise as the `$http.get()` method. You will need to get the original response of the `$resource.get()` method and then apply the `process` method again on this response. Then this should work.

Thanks and regards,

Guy

**Comment by markgargan** [comment]
Hey Guy,

      Could I ask you a question if you have time? 

<img width="919" alt="screen shot 2016-03-17 at 21 02 07" src="https://cloud.githubusercontent.com/assets/1690750/13862169/632b9bbe-ec89-11e5-8168-1d9b6d1e02ed.png">

I'm using SpringDataRestAdapter to interact with my spring data rest api. From the screen shot you can see that I've just loaded all the questions and I'm attempting to load their answers (one-to-many) relationship. In the debug window the _embeddedItems array is an array of Questions with _links to each questions answers. I'm trying to prompt SpringDataRestAdapter to autoload the answers by passing 'answers' as an argument to the processWithPromise call but to no avail.

The urls look like http://localhost:8080/api/questions http://localhost:8080/api/question/1/answers

The Question.loadAnswers(question) call is commented out... It works in that it loads the question's answers but I felt I was using the framework incorrectly.

Here is the method

```
Question.loadAnswers = function (question) {

            question.answers = question.answers? question.answers : [];

            angular.forEach(question._links.answers, function (answerLink) {
                var deferred = $http.get(answerLink);
                return SpringDataRestAdapter.processWithPromise(deferred).then(function (data) {
                    question.answers = data._embeddedItems;
                });
            });
        };
```

Congratulations on an excellent piece of coding Guy! I've also posted this question up on stackoverflow in case the issue is with my understanding of promises as opposed to how to use the framework :)

http://stackoverflow.com/questions/36072090/springdatarestadapter-load-child-resources

Thanks, Mark.

**Comment by guylabs** [comment]
Hi @sydneyhenrard,

do you have any update on this? Did it work the way I proposed?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi,

I will close the issue due to inactiviti. If you have anything to add please add a comment or reopen the issue.

Thanks and regards,

Guy
